ignore:
  - "src/interfaces/SuperAsset/**"
  - "src/interfaces/VaultBank/**"
  - "src/libraries/SuperAssetPriceLib.sol"
  - "src/SuperAsset/**"
  - "src/UP/**"
  - "src/vendor/**"
  - "src/VaultBank/**"
  - "test/**"