// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import { Test } from "forge-std/Test.sol";
import { MerkleProof } from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/// @title SuperBankMerkleTreeValidation
/// @notice Validates production-generated merkle trees for SuperBank hook authorization.
/// @dev Verifies leaf hash computation and merkle proof correctness for trees generated by superman.
///      Tests cover Ethereum (chain 1), Base (chain 8453), and HyperEVM (chain 999) for hook types:
///        - AcrossSendFundsAndExecuteOnDstHook (inspect returns: recipient, inputToken, outputToken, exclusiveRelayer)
///        - SwapOdosV2Hook (inspect returns: executor)
///        - ApproveAndSwapOdosV2Hook (inspect returns: tokenIn, tokenOut)
///        - SwapKyberSwapHook (inspect returns: dstToken)
///        - ApproveAndSwapKyberSwapHook (inspect returns: dstToken)
///        - ApproveERC20Hook (inspect returns: token, spender)
///
///      No fork needed — pure merkle math verification.
///
/// Run:
///   forge test --match-contract SuperBankMerkleTreeValidation -vvv
contract SuperBankMerkleTreeValidation is Test {
    // ═══════════════════════════════════════════════════════════════════
    //                         HELPERS
    // ═══════════════════════════════════════════════════════════════════

    /// @dev Matches Bank._createHookLeaf: keccak256(bytes.concat(keccak256(abi.encode(hookAddress, hookArgs))))
    function _createHookLeaf(address hookAddress, bytes memory hookArgs) internal pure returns (bytes32) {
        return keccak256(bytes.concat(keccak256(abi.encode(hookAddress, hookArgs))));
    }

    /// @dev Verifies a single leaf: recomputes leaf hash, checks it matches expected, then verifies merkle proof.
    function _verifyLeaf(
        address hookAddress,
        bytes memory encodedArgs,
        bytes32 expectedLeafHash,
        bytes32[] memory proof,
        bytes32 root
    )
        internal
        pure
    {
        bytes32 computedLeaf = _createHookLeaf(hookAddress, encodedArgs);
        assert(computedLeaf == expectedLeafHash);

        if (proof.length == 0) {
            assert(root == computedLeaf);
        } else {
            assert(MerkleProof.verify(proof, root, computedLeaf));
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //                  ETHEREUM (CHAIN 1) — ACROSS HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates AcrossSendFundsAndExecuteOnDstHook tree on Ethereum (676 leaves)
    /// @dev Hook: 0x39962bE24192d0d6B6e3a19f332e3c825604d16A
    ///      inspect() returns: abi.encodePacked(recipient, inputToken, outputToken, exclusiveRelayer)
    function test_eth_acrossHook_merkleTree() public pure {
        address hook = 0x39962bE24192d0d6B6e3a19f332e3c825604d16A;
        bytes32 root = 0x334d00baf43ce24e813560068690e349efa0eacc2af53334e576e94572939f74;

        // Leaf 0: first leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d158209b01357946a64a0793e9773f6f3fe5a5f2526ef101508bf4dc6cf0f0a0c135f39a41fab4e43890000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x001e0f87dc9499a309ef704a15e2ed6f686935266d5d45e45765406c8da1e26e;
            bytes32[] memory proof = new bytes32[](10);
            proof[0] = 0x00648c12b80de3aa65c19fdec5caca3f55771960819324564c829bef36ae0174;
            proof[1] = 0x2ddfe08ebe82a9b2c252bc3b90d2a21df6d77d62584644158f72a68378fbc0e7;
            proof[2] = 0x94893d057fc3e22eb16432f81a44110d57e0eca72c9b29ca8798827dcb0952e0;
            proof[3] = 0x795a8da7a4bd8e3531c488b724c25f46ea1201e1df96b8fca59800bdc5c40773;
            proof[4] = 0x1eb5c8908f18dec651acf5103c90a54082cc504d875aff5de9e9ee415424e6a2;
            proof[5] = 0x374fa08aa9f04cedb4d903156845c65c9d2705624c7104ef5ee904264c8bf3b4;
            proof[6] = 0xc6a745ace71d6f2ac42a5172d07aa61ab1fa0f358556f7ee23ca2c5d2213fb88;
            proof[7] = 0x2479b2f0c8211734a55e58a361e89b973f943aa28c44154c2dd2d05bf95de92b;
            proof[8] = 0x54af913781a7df86b9fb48e666d4bca97a36279c6b6fe9dedb663b7efb7b13a5;
            proof[9] = 0x882253bf28f8f3bea8fe45621a714913cc9017ad8997f58ab3eaf19e3e7af68a;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 675: last leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15a60c325069b2b10bc63926818a4f4320a28b5bba8209b01357946a64a0793e9773f6f3fe5a5f25260000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xffae59c0e67821e9b9da15fb78e3453a0c3f435822f393e51e377c50df5bfa15;
            bytes32[] memory proof = new bytes32[](5);
            proof[0] = 0xfec0d8a3992071279722e3cab190d0d1845cb84a05b42ea14cc95159aeac20f1;
            proof[1] = 0xf3e9390951b028bbe862c673fa3fd702d5ce12bb8883e57426e3d37be4679f29;
            proof[2] = 0x5ab7d7618d7350158cb2713acd2990d88f297692c7929f6279668907581baa5b;
            proof[3] = 0x58fc41136aec81383d7df2a56101029abb3752fcf9e6a7880bb89cdb67cad326;
            proof[4] = 0xdf318a5d417dc95ee20ecfce7e26caa425f11b375eb3b44d40cdd2609d442f1d;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //               ETHEREUM (CHAIN 1) — SWAP ODOS V2 HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates SwapOdosV2Hook tree on Ethereum (4 leaves — all tested)
    /// @dev Hook: 0x98313d15797048F60B1bFd41AE7A2B9877056079
    ///      inspect() returns: abi.encodePacked(executor)
    function test_eth_swapOdosV2Hook_merkleTree() public pure {
        address hook = 0x98313d15797048F60B1bFd41AE7A2B9877056079;
        bytes32 root = 0x47c6ebc68a7c0e886b708f1eaea43e3a176a129d10bf4b929efc7e329a5f307f;

        // Leaf 0: executor 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
        {
            bytes memory encodedArgs = hex"6131b5fae19ea4f9d964eac0408e4408b66337b5";
            bytes32 expectedLeaf = 0x1e66ee5011cb342290eae0cd0327b34e0b3023397c6329d4f3112228ddf58076;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0x50c4938378f202e5e867d354da2f599c1b0971083db2616e67d5b7b9990a94f2;
            proof[1] = 0x7cb7859dba0a3cd3a92ef5f6b9d0f15f506b1fd7a03c7ae9a2047ef23a9772af;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: executor 0xd4F480965D2347d421F1bEC7F545682E5Ec2151D
        {
            bytes memory encodedArgs = hex"d4f480965d2347d421f1bec7f545682e5ec2151d";
            bytes32 expectedLeaf = 0x50c4938378f202e5e867d354da2f599c1b0971083db2616e67d5b7b9990a94f2;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0x1e66ee5011cb342290eae0cd0327b34e0b3023397c6329d4f3112228ddf58076;
            proof[1] = 0x7cb7859dba0a3cd3a92ef5f6b9d0f15f506b1fd7a03c7ae9a2047ef23a9772af;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 2: executor 0x365084B05Fa7d5028346bD21D842eD0601bAB5b8
        {
            bytes memory encodedArgs = hex"365084b05fa7d5028346bd21d842ed0601bab5b8";
            bytes32 expectedLeaf = 0x9cc8d9dbc35d3c5e40de4e506ced5fd79ff9db3ca43c738136cbf726cf466d2c;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0xa747fe104b486ee0399ddc202915af3b97a859c94d1a42ba4a01dd890fb6c4d1;
            proof[1] = 0xb8ac0f8a308ff9bdf5cba419a8a52cc1c461ad2c7d21316618e016d23ba463a0;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 3: executor 0xCf5540fFFCdC3d510B18bFcA6d2b9987b0772559
        {
            bytes memory encodedArgs = hex"cf5540fffcdc3d510b18bfca6d2b9987b0772559";
            bytes32 expectedLeaf = 0xa747fe104b486ee0399ddc202915af3b97a859c94d1a42ba4a01dd890fb6c4d1;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0x9cc8d9dbc35d3c5e40de4e506ced5fd79ff9db3ca43c738136cbf726cf466d2c;
            proof[1] = 0xb8ac0f8a308ff9bdf5cba419a8a52cc1c461ad2c7d21316618e016d23ba463a0;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //          ETHEREUM (CHAIN 1) — APPROVE AND SWAP ODOS V2 HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndSwapOdosV2Hook tree on Ethereum (676 leaves)
    /// @dev Hook: 0xe138e0750a1311580A2c842FF10a9824Fc2C5217
    ///      inspect() returns: abi.encodePacked(tokenIn, tokenOut)
    function test_eth_approveAndSwapOdosV2Hook_merkleTree() public pure {
        address hook = 0xe138e0750a1311580A2c842FF10a9824Fc2C5217;
        bytes32 root = 0x219868f150d8985ace2e66e20c29964d07b83648a705964d10ab5090ae952dbf;

        // Leaf 0: first leaf
        {
            bytes memory encodedArgs =
                hex"469c74c25c6bdedff41ab69370ceea55f9f64e6ddac17f958d2ee523a2206206994597c13d831ec7";
            bytes32 expectedLeaf = 0x002a28bb8b60d438ec895ac73233bf2a8de6a6d3f0c0c112277151b09d90c420;
            bytes32[] memory proof = new bytes32[](10);
            proof[0] = 0x00e5ecf488c1f1c0a1fd4473d0a35a413fc2d3f3759570f9ef3f32cd899f0d26;
            proof[1] = 0xf37c8c6d52c1c268a8b98c5769c294c8d6905aa1abb0d0666ba2ab0f069f13d6;
            proof[2] = 0x10b4291ce6a90dab98ce397ad0aef539b8e5323490ebe0213388a335b6ba02f9;
            proof[3] = 0x741a957fecb8b9683fa2ff3fbff3cc17564c8c70880d3942f086dbdb646bd9e5;
            proof[4] = 0xfa161062bc0d4c7495967e234aac8409524d69da6bfaf9fcb563c87b928617c2;
            proof[5] = 0x83864a47a47bebd1afe770b6b342cb50b4330c58109fb346cc19172ff66f3590;
            proof[6] = 0xdc899971eb1f7c03c736a7f9eeef31fbcad5a464441a393acf3e1b2a9ecb8b58;
            proof[7] = 0xf7028daf768e85d6276cd8d3fdf63308f1a292b8227a7576b5406f3381816db4;
            proof[8] = 0x8eae6af52339134237035360b221b1aeca5dc38326e7e908a6a33915f7ea1379;
            proof[9] = 0x38bcdb7fab415e5917237f0e8fa1afdd757f6907570129172358dbf4e5bec23b;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 675: last leaf
        {
            bytes memory encodedArgs =
                hex"ef101508bf4dc6cf0f0a0c135f39a41fab4e4389526d0dde8876b6e8fb40026d62e625273d7f2460";
            bytes32 expectedLeaf = 0xfffb8671b54358e85ad289ee7331a329cd81f549325b84b3d486fc322d8ffbb8;
            bytes32[] memory proof = new bytes32[](5);
            proof[0] = 0xfff331ca5d37f677cca73c9824ca011fbcc717fed18084c6e34b22bc028fd823;
            proof[1] = 0x6377d4a786019c25716f6d770fefc124a8ec66d24d022c2f2dbf150e5bded534;
            proof[2] = 0xfc86b670b15a3f7c31c6753f3f3d189198d9c995af316a4f04230a3960526143;
            proof[3] = 0x6ab09e73e9969c296673ee51a235d7a511c82ce9d0980225ffba5462ab9425ca;
            proof[4] = 0xb2d61e5c5f3a0b838cc833d446e4b6327e214b7e06811663041f6501f6537eb1;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //                  BASE (CHAIN 8453) — ACROSS HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates AcrossSendFundsAndExecuteOnDstHook tree on Base (169 leaves)
    /// @dev Hook: 0xd724315eEebefe346985E028A7382158390cB892
    ///      inspect() returns: abi.encodePacked(recipient, inputToken, outputToken, exclusiveRelayer)
    function test_base_acrossHook_merkleTree() public pure {
        address hook = 0xd724315eEebefe346985E028A7382158390cB892;
        bytes32 root = 0x3f11d44e5b1c17e64a9b5ba9e7f8e74edc188492a176335829dfd5acedb97d7d;

        // Leaf 0: first leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15236aa50979d5f3de3bd1eeb40e81137f22ab794b1a5c5ea50717a2ea0e4f7036fb289349deaab58b0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x019bd803ee4bc241da2387032db40c05fd085f206e642dd7d8e4c14d77421607;
            bytes32[] memory proof = new bytes32[](8);
            proof[0] = 0x05d4d70ea0a920c81644003cd9f647aee67be9e733e8ba72a43c712bf529e5d1;
            proof[1] = 0xcf103f454a631cb0f506a033028abb681944438c42cd9c48d1174b60e88d2320;
            proof[2] = 0x15e34ed72315beb8114a6c14a367637278fd689329d1b89bca5665b85c5c7448;
            proof[3] = 0xd107663014e3eb5749894d7533221ac55f48401b660929a0a76f9012f4694250;
            proof[4] = 0x74ea592d89df7f15aff56e6d557032d9cd08bfe69a888c7257b0a31e96dcd347;
            proof[5] = 0x203260634f279d0bb8358b5d02adc93feeec96ec6fba7c4c1e304be257e915cb;
            proof[6] = 0x332a1fe3b4d346b5bbdfc0c47959bf2aceacdf234b25263f7f453253f51ec2ff;
            proof[7] = 0x68c4bbe4d45041a43fd99a66d2c1e2457d18b614400e9ce7f2cd70215cdeea97;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 168: last leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d151a5c5ea50717a2ea0e4f7036fb289349deaab58b1a5c5ea50717a2ea0e4f7036fb289349deaab58b0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xfff6ee3c98f1bc572d00cf8125e62fa4aa6d99adf02acd5f6521209a346a4c55;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x2b7a06c00bd6e7616a93bb68a4ffe04e48ea3d3c9b368535c0902a3936c06863;
            proof[1] = 0x12c48e6973a62287c782b0d4a07d933368ad1311a725c1e95b38f65701f3878e;
            proof[2] = 0x1bbb5957e5febd93c8b65ee2c3f628cf73d6217f41211c4b5422a228e9f3cbe8;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //                BASE (CHAIN 8453) — SWAP ODOS V2 HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates SwapOdosV2Hook tree on Base (5 leaves — all tested)
    /// @dev Hook: 0x074F9973EBfB050D7abc75a5cB03491d675DA843
    ///      inspect() returns: abi.encodePacked(executor)
    function test_base_swapOdosV2Hook_merkleTree() public pure {
        address hook = 0x074F9973EBfB050D7abc75a5cB03491d675DA843;
        bytes32 root = 0x43cd09102bdf9a7b87be532337a97fdec0c0f1d1b8d07ccfad7862d413816698;

        // Leaf 0: executor 0xe6151691FF20684426d5DC017c0a3C4E1e533dee (new Odos executor)
        {
            bytes memory encodedArgs = hex"e6151691ff20684426d5dc017c0a3c4e1e533dee";
            bytes32 expectedLeaf = 0x64261dfccff3b48e824a374513dd250b43c4181f8089f205e949eae157610009;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x822415c9b9d0f04cdb8d7850763588d2590f44ed2e074ac069d175202f9f584b;
            proof[1] = 0x5c23b76fb29f2eec3c95a57935f072973f0ba21767d256bdc2607af7014d7ba2;
            proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: executor 0x19cEeAd7105607Cd444F5ad10dd51356436095a1 (Odos Router V2)
        {
            bytes memory encodedArgs = hex"19ceead7105607cd444f5ad10dd51356436095a1";
            bytes32 expectedLeaf = 0x822415c9b9d0f04cdb8d7850763588d2590f44ed2e074ac069d175202f9f584b;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x64261dfccff3b48e824a374513dd250b43c4181f8089f205e949eae157610009;
            proof[1] = 0x5c23b76fb29f2eec3c95a57935f072973f0ba21767d256bdc2607af7014d7ba2;
            proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 2: executor 0xbF44De8fc9EEEED8615b0b3bc095CB0ddef35e09
        {
            bytes memory encodedArgs = hex"bf44de8fc9eeeed8615b0b3bc095cb0ddef35e09";
            bytes32 expectedLeaf = 0x83f1ab11e5deaa03b7cfc9574a037a510ad4759d278f287925c3fd113f6cc126;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0xd2705c4c0bb867a7e891f71cd74abdd001cbb2ce530aadc4f43c5b49163d321c;
            proof[1] = 0x877c94e2893505a22222c534a1752cbd516983cdb2d5e3afb3a7626dc95bece7;
            proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 3: executor 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5 (KyberSwap)
        {
            bytes memory encodedArgs = hex"6131b5fae19ea4f9d964eac0408e4408b66337b5";
            bytes32 expectedLeaf = 0xd2705c4c0bb867a7e891f71cd74abdd001cbb2ce530aadc4f43c5b49163d321c;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x83f1ab11e5deaa03b7cfc9574a037a510ad4759d278f287925c3fd113f6cc126;
            proof[1] = 0x877c94e2893505a22222c534a1752cbd516983cdb2d5e3afb3a7626dc95bece7;
            proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 4: executor 0xd4F480965D2347d421F1bEC7F545682E5Ec2151D (Pendle)
        {
            bytes memory encodedArgs = hex"d4f480965d2347d421f1bec7f545682e5ec2151d";
            bytes32 expectedLeaf = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0x073f89ad109be8c177fc3f6449435002143e9219cc7832ca0aea6495e9541fe5;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //     BASE (CHAIN 8453) — APPROVE AND SWAP ODOS V2 HOOK (executor-only)
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndSwapOdosV2Hook tree on Base (5 leaves — all tested)
    /// @dev Hook: 0x3E10d4105F826dFc8929845C94c019CDAF4d93cD
    ///      inspect() returns: abi.encodePacked(executor)
    function test_base_approveAndSwapOdosV2Hook_executorOnly_merkleTree() public pure {
        address hook = 0x3E10d4105F826dFc8929845C94c019CDAF4d93cD;
        bytes32 root = 0xbcd0d55543bd09819e78d186612fafc93fded69baf9594fa1f608d961cb5d85e;

        // Leaf 0: executor 0xe6151691FF20684426d5DC017c0a3C4E1e533dee (new Odos executor)
        {
            bytes memory encodedArgs = hex"e6151691ff20684426d5dc017c0a3c4e1e533dee";
            bytes32 expectedLeaf = 0x1b0e02d3a3de4fd618846b528cf01fe3f510e1a2187f329c9ee1f9005c95664e;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x24682b1e256fb5c659e2165b0dddede5c0f82820824646b0cc5d13784f9dcf4c;
            proof[1] = 0x4b4c40612905ca397f3ff95f9e54c3e10de4942ba0c7182db1e14e6d41aa5d9c;
            proof[2] = 0xebd0159addcdb0b8d49c51e6e6ed044a94e332e17992f53cf58beb0b68f14931;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: executor 0xd4F480965D2347d421F1bEC7F545682E5Ec2151D (Pendle)
        {
            bytes memory encodedArgs = hex"d4f480965d2347d421f1bec7f545682e5ec2151d";
            bytes32 expectedLeaf = 0x24682b1e256fb5c659e2165b0dddede5c0f82820824646b0cc5d13784f9dcf4c;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x1b0e02d3a3de4fd618846b528cf01fe3f510e1a2187f329c9ee1f9005c95664e;
            proof[1] = 0x4b4c40612905ca397f3ff95f9e54c3e10de4942ba0c7182db1e14e6d41aa5d9c;
            proof[2] = 0xebd0159addcdb0b8d49c51e6e6ed044a94e332e17992f53cf58beb0b68f14931;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 2: executor 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5 (KyberSwap)
        {
            bytes memory encodedArgs = hex"6131b5fae19ea4f9d964eac0408e4408b66337b5";
            bytes32 expectedLeaf = 0x8a2bf8eafa210db554fd3bf97d0d8097de1dce2f44f351120910959da8e6460c;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0xa42e6d141602dcb0d20cfd29650d65a6efee507b7b204bed042670632015714f;
            proof[1] = 0x9df0753515d9110e6ea11d8d7b5772ef479621919a6cc8a995843ac2197e4a4a;
            proof[2] = 0xebd0159addcdb0b8d49c51e6e6ed044a94e332e17992f53cf58beb0b68f14931;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 3: executor 0x19cEeAd7105607Cd444F5ad10dd51356436095a1 (Odos Router V2)
        {
            bytes memory encodedArgs = hex"19ceead7105607cd444f5ad10dd51356436095a1";
            bytes32 expectedLeaf = 0xa42e6d141602dcb0d20cfd29650d65a6efee507b7b204bed042670632015714f;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x8a2bf8eafa210db554fd3bf97d0d8097de1dce2f44f351120910959da8e6460c;
            proof[1] = 0x9df0753515d9110e6ea11d8d7b5772ef479621919a6cc8a995843ac2197e4a4a;
            proof[2] = 0xebd0159addcdb0b8d49c51e6e6ed044a94e332e17992f53cf58beb0b68f14931;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 4: executor 0xbF44De8fc9EEEED8615b0b3bc095CB0ddef35e09
        {
            bytes memory encodedArgs = hex"bf44de8fc9eeeed8615b0b3bc095cb0ddef35e09";
            bytes32 expectedLeaf = 0xebd0159addcdb0b8d49c51e6e6ed044a94e332e17992f53cf58beb0b68f14931;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0xe7022f2f4d1b2eb4fbd13e723cf7d4c962ce3b4f238797d0d41acf62ce3841c7;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //     BASE (CHAIN 8453) — APPROVE AND SWAP ODOS V2 HOOK (legacy 0x8211)
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates legacy ApproveAndSwapOdosV2Hook tree on Base (169 leaves)
    /// @dev Hook: 0x8211082177F01eEd24B73491f8eD79eE535BD980
    ///      inspect() returns: abi.encodePacked(tokenIn, tokenOut)
    function test_base_approveAndSwapOdosV2Hook_merkleTree() public pure {
        address hook = 0x8211082177F01eEd24B73491f8eD79eE535BD980;
        bytes32 root = 0xa33ca8e8c90d7d1ffacc6bd26ae53fa67a01cf26af75fd6ce2dcbae63dac6b62;

        // Leaf 0: first leaf (cbBTC -> WETH)
        {
            bytes memory encodedArgs =
                hex"cbb7c0000ab88b473b1f5afd9ef808440eed33bf4200000000000000000000000000000000000006";
            bytes32 expectedLeaf = 0x0198ab67d883fe2587293dae2346e9f6d6bde2395f2f9a3b127ab336bc351e6a;
            bytes32[] memory proof = new bytes32[](8);
            proof[0] = 0x020774477f2aa1a5a7435a298f0df6a7809ea5f409859e3cacf320298705d426;
            proof[1] = 0xb5d6c83d2107bd7414a881b492a459475aa8c09789bec26df2c33e6069e5e339;
            proof[2] = 0x17c7a69278f2fd1ab3c190da05c7e82c8f01664106bcfa63575131ad55bfec0c;
            proof[3] = 0xd70abae5ce2d98330ceb2b1bd0d2c6a89fe6883a93e969a0ac018b90946d6740;
            proof[4] = 0x0e239dffb5dbf59fbfc6f48cf3da303df316be0617db80684886e5c2c041b84b;
            proof[5] = 0x09d2df5bcabe2a54f7e3ae3848ae79740ef436a8858a569744569076f4cfd904;
            proof[6] = 0x80023feb29e2ece03a1b07e03d04db381160dc2656ae3c795933ebc94e0dca11;
            proof[7] = 0x43971906c23fce4588cba2f7114e819330a8d1ded220e87c04bda1e96eee7d69;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 168: last leaf
        {
            bytes memory encodedArgs =
                hex"0000000f0adfc34d90f04f98e4a409e8b5b2c72ff2a69e0191aad3a7a124397972d0ca0405c1d8d1";
            bytes32 expectedLeaf = 0xffd6333ce098d29aa595954098f1c81aefb9e595d0cfb24a05424a61d1c45b85;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0xcef07dd602aaaf26be205e524dcd9505a7e8762cac620ce1c48c7e1d5bd4fc4a;
            proof[1] = 0x48820dafb281c66c96a13ccd53b5da40936f869cd44e6b2b26022f7009999818;
            proof[2] = 0x59c09a71e5e46983dadcbe1134137780e6d6e0568af776f273e0b4abe50ba043;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //     HYPEREVM (CHAIN 999) — APPROVE AND SWAP KYBERSWAP HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndSwapKyberSwapHook tree on HyperEVM (2 leaves — all tested)
    /// @dev Hook: 0xF3818ac90DCA76a7Efe40C3cB2548F96B2236595
    ///      inspect() returns: abi.encodePacked(dstToken)
    function test_hyperevm_approveAndSwapKyberSwapHook_merkleTree() public pure {
        address hook = 0xF3818ac90DCA76a7Efe40C3cB2548F96B2236595;
        bytes32 root = 0xfd0cee7ef52e43e35f4bb5259fd373a4f4ee2f21bc3164d3b2f3036ee9a985f8;

        // Leaf 0: dst_token = UP (UpOft 0x642fFC3496AcA19106BAB7A42F1F221a329654fe)
        {
            bytes memory encodedArgs = hex"642ffc3496aca19106bab7a42f1f221a329654fe";
            bytes32 expectedLeaf = 0x306d0515d6386244f4cbe03bd0803eeb7a4b879f3e009e7cf143e8079401f810;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0xf8941e7df08cd5767243a79f66843c9ab424c485bb155f8d978bd7fbf325145f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: dst_token = USDC (0xb88339CB7199b77E23DB6E890353E22632Ba630f)
        {
            bytes memory encodedArgs = hex"b88339cb7199b77e23db6e890353e22632ba630f";
            bytes32 expectedLeaf = 0xf8941e7df08cd5767243a79f66843c9ab424c485bb155f8d978bd7fbf325145f;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0x306d0515d6386244f4cbe03bd0803eeb7a4b879f3e009e7cf143e8079401f810;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //          HYPEREVM (CHAIN 999) — SWAP KYBERSWAP HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates SwapKyberSwapHook tree on HyperEVM (2 leaves — all tested)
    /// @dev Hook: 0x1851A7fa26B507b681187585e3B368B95FbfdBB0
    ///      inspect() returns: abi.encodePacked(dstToken)
    function test_hyperevm_swapKyberSwapHook_merkleTree() public pure {
        address hook = 0x1851A7fa26B507b681187585e3B368B95FbfdBB0;
        bytes32 root = 0x89ef5092e84840c57e8fac67b3069b08cb62fc6c07c3f8506dd8509ea770ff0f;

        // Leaf 0: dst_token = UP (UpOft 0x642fFC3496AcA19106BAB7A42F1F221a329654fe)
        {
            bytes memory encodedArgs = hex"642ffc3496aca19106bab7a42f1f221a329654fe";
            bytes32 expectedLeaf = 0x0b464181c33f0db5fd352d995e39bca073db54b9eb168b97a78aac1ce067d0f5;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0xffd3488227d0d5432e3d8bfbeb28132cdf4d94c0ec5084382d8871e99a20ad43;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: dst_token = USDC (0xb88339CB7199b77E23DB6E890353E22632Ba630f)
        {
            bytes memory encodedArgs = hex"b88339cb7199b77e23db6e890353e22632ba630f";
            bytes32 expectedLeaf = 0xffd3488227d0d5432e3d8bfbeb28132cdf4d94c0ec5084382d8871e99a20ad43;
            bytes32[] memory proof = new bytes32[](1);
            proof[0] = 0x0b464181c33f0db5fd352d995e39bca073db54b9eb168b97a78aac1ce067d0f5;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //     HYPEREVM (CHAIN 999) — APPROVE ERC20 HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveERC20Hook tree on HyperEVM (10 leaves — first and last tested)
    /// @dev Hook: 0x8b789980dc6cC7d88E30C442D704646ff7F6d306
    ///      inspect() returns: abi.encodePacked(token, spender)
    function test_hyperevm_approveERC20Hook_merkleTree() public pure {
        address hook = 0x8b789980dc6cC7d88E30C442D704646ff7F6d306;
        bytes32 root = 0x1ce055e97c45de28b011b800771200feb493f26913c683dd30aac4af9bb0b485;

        // Leaf 0: UP approved for SpokePool (0x5c7BCd6E7De5423a257D81B442095A1a6ced35C5)
        {
            bytes memory encodedArgs =
                hex"642ffc3496aca19106bab7a42f1f221a329654fe5c7bcd6e7de5423a257d81b442095a1a6ced35c5";
            bytes32 expectedLeaf = 0x0e1c7e7a135bfab4f9bf8fe2b4b9774bbe6559bed267e2fb75248768ab081e1c;
            bytes32[] memory proof = new bytes32[](4);
            proof[0] = 0x3e91197e2dd08a047a809d2c3b25d6edb90d533fb4636193281f65e38e244833;
            proof[1] = 0xd914010aa1ec2326364fea64d0dfa6b82cc4b3bf29957ea11fca23953069746a;
            proof[2] = 0x0acf72e40ff0599e38e916a246ff7a8ad5cd7dd087938c15ab6ae51976806a8a;
            proof[3] = 0x514c6cff09711b4e99f26c682857c19f3e82f99148e7487fa182da11e41bfe93;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 9: UP approved for SuperBank (0x6fCc6a6A825FC14e6e56Fd14978FC6B97ACB5d15)
        {
            bytes memory encodedArgs =
                hex"642ffc3496aca19106bab7a42f1f221a329654fe6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15";
            bytes32 expectedLeaf = 0xeb26586bab949837d7a242d0933979714f59110fffff0ed71326b88dedf83c5e;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0xcf28d3d63604b51374adcf2238724b48115dba4bca38839f60269992f613a6aa;
            proof[1] = 0xf2b13a895fe4b8a12b31586335884b2a8de701277c26134c832f6bca5cb29d32;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  ETHEREUM (CHAIN 1) — APPROVE AND ACROSS SEND FUNDS HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndAcrossSendFundsAndExecuteOnDstHook tree on Ethereum (1122 leaves)
    /// @dev Hook: 0x72422aB917e4a698369767F7AcE667a769E0F3f2
    ///      inspect() returns: abi.encodePacked(recipient, inputToken, outputToken, exclusiveRelayer)
    function test_eth_approveAndAcrossHook_merkleTree() public pure {
        address hook = 0x72422aB917e4a698369767F7AcE667a769E0F3f2;
        bytes32 root = 0x9878e7490ce4be12530b2e7bc670855c1b4c9c044a593c47c2c9b0abbfe37877;

        // Leaf 0: first leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15cccc62962d17b8914c62d74ffb843d73b2a3ccccb6c0b59aff5c128ab0631a7ce762a2abcf926d840000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x00030c9e22bda2b2630b0351b4b7e1fd7c32dbe251fa7f97f9a541c44e0867d6;
            bytes32[] memory proof = new bytes32[](11);
            proof[0] = 0x00032d303face379106128afd6af070a3a23ba83986416afa902115df42e4c27;
            proof[1] = 0x7012c7ff83c668157fbcc625f87cbcefc8898b58c3001b1970df81067238b6bb;
            proof[2] = 0x104719ab3053f4bd3b3c28bdf9bb79660def032b774fd01d3b153b578d759660;
            proof[3] = 0xf71decceddd726b4083332833385643a99a4e0aec32785437b3e3259f7277ca4;
            proof[4] = 0x924c90e6ff49519c3bddf1f194ff8d9147b74a8ef12c97b84bb525b51d47815c;
            proof[5] = 0x7c0716d413b3420f78e748c12dc3ec0627002305479ff9cacc56576e438afb2c;
            proof[6] = 0xf8abb3b629be43c861be77bcf4e597bdc67312cb46f276b8799cd4b419a883fe;
            proof[7] = 0x906b66cbbab0ce4f57998a0e27d684b95a25c070df05beef95b7f4ff46b8fbb1;
            proof[8] = 0xf4bf1a9800ee392588f13e1eb9f8ea049f3127b8ea4c3a4e21b9ea30b22a267e;
            proof[9] = 0x19a6ca198114d31cd0a622f608ff5d8109d20632a4a0de45cd8a10237a9cfe60;
            proof[10] = 0xfaae5afb421149c014a7deb594cf48523b31b9dd06e55cb770ed8811bb72d044;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1121: last leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xfff1f7904660311ba304619e1b9edb56e718177dc361c3e16e4504a58c3de90f;
            bytes32[] memory proof = new bytes32[](4);
            proof[0] = 0xffe7df0ba9d0cc58c2586340ea99d978a7c6ff9728004ae96b16839a9cbe2f4f;
            proof[1] = 0x28162cce6c9af9a8d8a641befb4d6e04f493556580f422401e2d63caa610a8a4;
            proof[2] = 0xf3f416e00b111961e59796558c69cc4a410ed725362ceb35ade94c36b65b323f;
            proof[3] = 0x5bfe3d14ccba06e1d3891b67cea2c61f7b0e7bcdb63558f282ca565ceb12329f;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  BASE (CHAIN 8453) — APPROVE AND ACROSS SEND FUNDS HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndAcrossSendFundsAndExecuteOnDstHook tree on Base (169 leaves)
    /// @dev Hook: 0x2286d45D7dCaE6aabb6B72269Bc07a401C16e481
    ///      inspect() returns: abi.encodePacked(recipient, inputToken, outputToken, exclusiveRelayer)
    function test_base_approveAndAcrossHook_merkleTree() public pure {
        address hook = 0x2286d45D7dCaE6aabb6B72269Bc07a401C16e481;
        bytes32 root = 0x0e5e1b146db81b362ae65ba2b09adf67bdf9e29f698848cd65759bbbabd475c1;

        // Leaf 0: first leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15833589fcd6edb6e08f4c7c32d4f71b54bda029135b2193fdc451c1f847be09ca9d13a4bf60f8c86b0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x0004dc5fc779ea3a4f4a97f6a6eb87667d99664d7ebc6526fabf1726cca6565c;
            bytes32[] memory proof = new bytes32[](8);
            proof[0] = 0x00a633fae991df547217b73b9bbe803ffd33966f46306ebf8610584373c521ff;
            proof[1] = 0x90078bffab3b120c2558fe7f8d2cfec8646970534a6ec21fd794150421c80f7d;
            proof[2] = 0x9fd03801b12ff6d2ac946c38792beb574628d74be54b0d36dad888f24b0a8ae3;
            proof[3] = 0xb5b8cc5490674614036b7fbed1fd9da27ab85fdab4f8dc248c343e24077ccfc5;
            proof[4] = 0x622db2a2b1f20d298130bd0ae54bbf9d282cab86af5785ddc3b3951ce83787ef;
            proof[5] = 0x4cea6c225ab705ad2884865556e5f687da51e4d9a082b5848f9365342ff99e77;
            proof[6] = 0x993283b3d067a83e496ebeaec1a9ed1f88b010a17036bc1fbf6e8977fef0edf8;
            proof[7] = 0x09a6594ddd7ead48c5b429bd57ac437721e5b6ce3f2b71bd866d889ca00a4ef3;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 168: last leaf
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15cbb7c0000ab88b473b1f5afd9ef808440eed33bf42000000000000000000000000000000000000060000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xfc653aea98b6167084bab938613093347e67ca8a1c048ae0410af1cc86a4ddd4;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0xdc4f7afa969b513f1061a2c8ded8d8b5b64178d16973f165b52a9c11949dfd7e;
            proof[1] = 0xa2006a4b4d0b5e89514ae2db0c7267e5201275efa4e80df72455099935621c14;
            proof[2] = 0xeff09e494c30afd80f007101d003bd11cc73d06a176d16d5eaf6c9339fd2e90b;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  HYPEREVM (CHAIN 999) — APPROVE AND ACROSS SEND FUNDS HOOK
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Validates ApproveAndAcrossSendFundsAndExecuteOnDstHook tree on HyperEVM (6 leaves — all tested)
    /// @dev Hook: 0x77c932e8F7A308Ddf0EB4cd94ea0526Ed676eFeE
    ///      inspect() returns: abi.encodePacked(recipient, inputToken, outputToken, exclusiveRelayer)
    function test_hyperevm_approveAndAcrossHook_merkleTree() public pure {
        address hook = 0x77c932e8F7A308Ddf0EB4cd94ea0526Ed676eFeE;
        bytes32 root = 0x893631ba68fd73c2e74dcf604a4b5ef869f5254463eedfe50a1edca19db166e8;

        // Leaf 0: UP -> UP
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15642ffc3496aca19106bab7a42f1f221a329654fe642ffc3496aca19106bab7a42f1f221a329654fe0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x0920b155dda9bd10de0168361a84ff7b3d33007b28b835d45a9fa52aa49785f8;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x12b27d6ee8033a4d1cf897bf3c8c5fc31a7817a69798299b672f9be066a14e82;
            proof[1] = 0x711576b6b7a78ee1599842e384cec22f835e734a0a456738cac7330f1cbfc0e6;
            proof[2] = 0x6b28bb609a816f36c28b17ebeee574a93ef88fcbf9cc0106d466d3df1a34f135;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 1: UP -> USDC
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15642ffc3496aca19106bab7a42f1f221a329654feb88339cb7199b77e23db6e890353e22632ba630f0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x12b27d6ee8033a4d1cf897bf3c8c5fc31a7817a69798299b672f9be066a14e82;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x0920b155dda9bd10de0168361a84ff7b3d33007b28b835d45a9fa52aa49785f8;
            proof[1] = 0x711576b6b7a78ee1599842e384cec22f835e734a0a456738cac7330f1cbfc0e6;
            proof[2] = 0x6b28bb609a816f36c28b17ebeee574a93ef88fcbf9cc0106d466d3df1a34f135;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 2: UP -> Base USDC (cross-chain)
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15642ffc3496aca19106bab7a42f1f221a329654fe833589fcd6edb6e08f4c7c32d4f71b54bda029130000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x23dde7cbf92948c59b44ffbb39d6276dd72632fbcc2ab7849c83fc3c9029704e;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x98a25398bd6d40c65ecf98439c336819d5b5e09b39e6d091b188d47b4ba01b67;
            proof[1] = 0x18a43dbd842634bb5f0412792da357258389f9cd104439bc575ce5dc033065b7;
            proof[2] = 0x6b28bb609a816f36c28b17ebeee574a93ef88fcbf9cc0106d466d3df1a34f135;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 3: USDC -> Base USDC (cross-chain)
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15b88339cb7199b77e23db6e890353e22632ba630f833589fcd6edb6e08f4c7c32d4f71b54bda029130000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0x98a25398bd6d40c65ecf98439c336819d5b5e09b39e6d091b188d47b4ba01b67;
            bytes32[] memory proof = new bytes32[](3);
            proof[0] = 0x23dde7cbf92948c59b44ffbb39d6276dd72632fbcc2ab7849c83fc3c9029704e;
            proof[1] = 0x18a43dbd842634bb5f0412792da357258389f9cd104439bc575ce5dc033065b7;
            proof[2] = 0x6b28bb609a816f36c28b17ebeee574a93ef88fcbf9cc0106d466d3df1a34f135;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 4: USDC -> UP
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15b88339cb7199b77e23db6e890353e22632ba630f642ffc3496aca19106bab7a42f1f221a329654fe0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xb4b229b040f0c17327ee562bc154c6253bad850a4b869ac1be7209ef9f8719ec;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0xdff5314b731b2ed2661beb121ce48e5370642a88cbd390bbfdd5061fff99e5e1;
            proof[1] = 0xc41ba5b8e29850de936ce9bd9d41d995c41ad2f81c66c6f4f1ebaf2d3123d56d;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }

        // Leaf 5: USDC -> USDC
        {
            bytes memory encodedArgs =
                hex"6fcc6a6a825fc14e6e56fd14978fc6b97acb5d15b88339cb7199b77e23db6e890353e22632ba630fb88339cb7199b77e23db6e890353e22632ba630f0000000000000000000000000000000000000000";
            bytes32 expectedLeaf = 0xdff5314b731b2ed2661beb121ce48e5370642a88cbd390bbfdd5061fff99e5e1;
            bytes32[] memory proof = new bytes32[](2);
            proof[0] = 0xb4b229b040f0c17327ee562bc154c6253bad850a4b869ac1be7209ef9f8719ec;
            proof[1] = 0xc41ba5b8e29850de936ce9bd9d41d995c41ad2f81c66c6f4f1ebaf2d3123d56d;
            _verifyLeaf(hook, encodedArgs, expectedLeaf, proof, root);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //                     NEGATIVE TESTS
    // ═══════════════════════════════════════════════════════════════════

    /// @notice Verifies that a tampered leaf fails merkle proof verification
    function test_invalidLeaf_failsMerkleProof() public pure {
        // Use Base SwapOdosV2 tree
        bytes32 root = 0x43cd09102bdf9a7b87be532337a97fdec0c0f1d1b8d07ccfad7862d413816698;
        address hook = 0x074F9973EBfB050D7abc75a5cB03491d675DA843;

        // Valid proof for leaf 0 but with a wrong executor address
        bytes memory wrongArgs = hex"deadbeefdeadbeefdeadbeefdeadbeefdeadbeef";
        bytes32 wrongLeaf = _createHookLeaf(hook, wrongArgs);

        bytes32[] memory proof = new bytes32[](3);
        proof[0] = 0x822415c9b9d0f04cdb8d7850763588d2590f44ed2e074ac069d175202f9f584b;
        proof[1] = 0x5c23b76fb29f2eec3c95a57935f072973f0ba21767d256bdc2607af7014d7ba2;
        proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;

        assert(!MerkleProof.verify(proof, root, wrongLeaf));
    }

    /// @notice Verifies that a valid leaf with the wrong root fails
    function test_wrongRoot_failsMerkleProof() public pure {
        address hook = 0x074F9973EBfB050D7abc75a5cB03491d675DA843;
        bytes32 wrongRoot = 0x1111111111111111111111111111111111111111111111111111111111111111;

        bytes memory encodedArgs = hex"19ceead7105607cd444f5ad10dd51356436095a1";
        bytes32 leaf = _createHookLeaf(hook, encodedArgs);

        bytes32[] memory proof = new bytes32[](3);
        proof[0] = 0x64261dfccff3b48e824a374513dd250b43c4181f8089f205e949eae157610009;
        proof[1] = 0x5c23b76fb29f2eec3c95a57935f072973f0ba21767d256bdc2607af7014d7ba2;
        proof[2] = 0xda2c835670e3df155414b4f235d43561fc870de2160a43846dd89ee4c7cfed2f;

        assert(!MerkleProof.verify(proof, wrongRoot, leaf));
    }
}
